title: Документация по Лабораторной Работе 1
description: Документация по Лабораторной Работе 1 - Система Управления Задачами
theme: jekyll-theme-minimal
baseurl: "/ITMO_ICT_WebDevelopment_tools_2024-2025/students/k3342/Senichev_Sergey/Lr1/docs"
url: "" 