title: Документация по лабораторным работам
description: Документация по лабораторным работам курса "Инструменты веб-разработки"
theme: jekyll-theme-cayman
baseurl: "/docs"
url: "https://ssenichev.github.io" 