title: Документация по лабораторным работам
description: Документация по лабораторным работам курса "Инструменты веб-разработки"
theme: jekyll-theme-cayman
baseurl: "/ITMO_ICT_WebDevelopment_tools_2024-2025/docs"
url: "https://ssenichev.github.io" 